### ISSUE TITLE
Prefetch related not working for parental many to many relations

### ISSUE THREAD

**Issue by RadoRado** [wagtail/django-modelcluster#101]
:wave: 

I want to apologize in advance, if I'm missing something obvious, but having the following example:

```python
from django.db import models

from modelcluster.models import ClusterableModel
from modelcluster.fields import ParentalManyToManyField

class Movie(ClusterableModel):
   name = models.CharField(max_length=250)
   actors = ParentalManyToManyField('Actors', related_name='movies')


class Actors(models.Model):
   name = models.CharField(max_length=250)
```

When I do

```python
Movie.objects.prefetch_related('actors')
```

I get the following error:

```
ValueError: 'actors' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
```

The question is - how am I supposed to do the `prefetch_related` on `ParentalManyToManyField`?

The context is Wagtail, but I'm posting this here, since the issues seems to be from the clusterable model.

Thanks!

**Comment by cho-leukeleu** [comment]
I also ran into this issue and could work around it by indexing a callable (as documented there https://docs.wagtail.io/en/v2.3/topics/search/indexing.html#indexing-callables-and-other-attributes). 
For an Actor model as simple as the one demonstrated here, it might help as well :/.

**Comment by cho-leukeleu** [comment]
@cnk you are correct about the documentation being about ES but we are using [wagtail-pg-search-backend](https://github.com/wagtail/wagtail-pg-search-backend) and it happens to also apply there. Our project is using Wagtail 1.12.3 (even though I was linking to a more recent version of the docs) and we have the same model structure except instead of manually calling `Movie.objects.prefetch_related('actors')`, we want to be able to find Movies by querying Actor names. We tried indexing the model like this:

    search_fields = [
        index.RelatedFields('actors', [
            index.SearchField('name'),
        ]),
    ]

Which eventually yields the same error as reported when we build the index with `update_index`.

What I meant by indexing a callable was this:

    search_fields = [
        index.SearchField('get_related_actors'),
    ]

    # Get list of ParentalManyToManyField and concatenate them for indexation
    def get_related_actors(self):
        return '\n'.join(self.actors.all().values_list('name', flat=True))

though googling lead me here, I see now that this issue is only remotely related to my issue 😅.

**Comment by FlipperPA** [comment]
@RadoRado Did you ever find a clean way of doing this?

**Comment by acarasimon96** [comment]
It seems that I've discovered the culprit of this nasty bug.

Following @RadoRado's example above, I've noticed that swapping out `ParentalManyToManyField` to `models.ManyToManyField` allowed the use of `prefetch_related` in exchange of losing the ability to see the not-yet-saved `Actors` objects in Wagtail previews. But with some debugging using `pdb`, I found out that `DeferringRelatedManager` in `fields.create_deferring_forward_many_to_many_manager` is missing a `get_prefetch_queryset` function, which the Django ORM needs when attempting to reference a `ParentalManyToManyField` field through `prefetch_related` -- in this case, `Movie.actors`. `ManyRelatedManager` (in which `DeferringRelatedManager` is based from I think) does have that missing function.

So you may be wondering at this point where in the Django source code does this check happen. It turns out that occurs in `django.db.models.query.get_prefetcher` (specifically [line 1700 as of Django 2.2](https://github.com/django/django/blob/stable/2.2.x/django/db/models/query.py#L1700))

**Comment by harrislapiroff** [comment]
Ran into this today! Would be very excited to see @chosak's PR cross the finish line.

**Comment by gasman** [comment]
Completed in #122.
