### ISSUE TITLE
Preview breaks on latest 6.2 version

### ISSUE THREAD

**Issue by MasonLyons** [wagtail/django-modelcluster#182]
When previewing the page using the latest 6.2 version we get the following error

`'_ClusterTaggableManager' object has no attribute '_remove_prefetched_objects'`

The issue disparages on 6.1

Python: 3.11
Django: 4.2.9
Wagtail: 5.2.2

**Comment by gasman** [comment]
Thanks for the report!

What version of django-taggit are you running? Looks like `_remove_prefetched_objects` has existed since django-taggit 3.1.0 - https://github.com/jazzband/django-taggit/commit/3a5163abfe3fcc72579fd07d1bbc21d867e544d0

**Comment by MasonLyons** [comment]
We're using 2.1.0
The wagtail setup .py uses
`"django-taggit>=2.0,<5.1",`
we were automatically pulling it from there with pip-compile
I've tweaked our process so we pull the most recent version now but it may still need an upgrade in wagtail to prevent it.
Thanks.

**Comment by gasman** [comment]
Have now released 6.2.1 with #183, which makes a version check before calling `_remove_prefetched_objects`. Will also bump the dependency in Wagtail's setup.py, although since that's technically a breaking change (people might be relying on django-taggit's pre-3.x handling of slugs) this will only take effect in the upcoming Wagtail 6.0.
